cpdef vectorize(object x)
cpdef H(object z, object params=*)
cpdef E(object z, object params=*)
cpdef omega_m_z(object z, object params=*)
cpdef omega_l_z(object z, object params=*)
cpdef mass_to_radius(M, mean_dens)
cpdef radius_to_mass(R, mean_dens)
